sudo: required

dist: focal
addons:
  apt:
    update: true

language: python

jobs:
  include:
    - stage: test
      
before_install:
  - pwd
  - ls
  - openssl aes-256-cbc -K $encrypted_b0a9ad5fb694_key -iv $encrypted_b0a9ad5fb694_iv -in uploaddownloadapp.2021-06-10.private-key.pem.enc -out ./uploaddownloadapp.2021-06-10.private-key.pem -d
  - git clone https://github.com/lanl/Py-CGAD.git
  - ls

install:
  - ls
  - sudo apt-get install gnutls-bin libghc-gnutls-dev
  - python3 -m pip install cryptography --upgrade
  - python3 -m pip install Py-CGAD/  # --user flag is not allowed in travis virtual env
  
script:
  - echo "Display env variables"
  - env
  - python3 -m pytest -s
  - PYTHONPATH=$PYTHONPATH:upload_download python3 ./bin/upload_download.py --permissions statusreportingapp.2021-05-29.private-key.pem
